-- Visit ID (bqvid): one per visit, generated by pixel, links click (bqcid) to visit for attribution.
ALTER TABLE public.visit_source_events
  ADD COLUMN IF NOT EXISTS visit_id text,
  ADD COLUMN IF NOT EXISTS click_id text;

CREATE INDEX IF NOT EXISTS idx_visit_source_events_visit_id ON public.visit_source_events(visit_id);
CREATE INDEX IF NOT EXISTS idx_visit_source_events_click_id ON public.visit_source_events(click_id);

COMMENT ON COLUMN public.visit_source_events.visit_id IS 'bqvid: generated on pixel, identifies this visit for attribution.';
COMMENT ON COLUMN public.visit_source_events.click_id IS 'bqcid from redirect URL; links this visit to redirect_click_events.';
